name: website
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  lottie: ^2.7.0
  responsive_builder: 0.7.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
  - family: Open_Sans
    fonts:
    - asset: assets/fonts/Open_Sans/OpenSans-Italic-VariableFont_wdth,wght.ttf
    - asset: assets/fonts/Open_Sans/OpenSans-Italic-VariableFont_wdth,wght.ttf
    #- asset: assets/fonts/Open_Sans/static/
